name: dart_faye
description: A complete Dart implementation of Faye, a publish-subscribe messaging system that implements the Bayeux protocol.
version: 1.2.3
homepage: https://mikewhob.com/dart_faye
repository: https://github.com/mwhobrey/dart_faye
issue_tracker: https://github.com/mwhobrey/dart_faye/issues
documentation: https://mikewhob.com/dart_faye
license: MIT
keywords:
  - faye
  - bayeux
  - real-time
  - messaging
  - pubsub
  - websocket
  - http
  - dart
  - flutter
topics:
  - real-time
  - messaging
  - networking

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  http: ^1.2.0
  web_socket_channel: ^3.0.3
  uuid: ^4.3.3
  logging: ^1.2.0
  meta: ^1.12.0

dev_dependencies:
  test: ^1.24.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  lints: ^6.0.0
  crypto: ^3.0.3
  convert: ^3.1.1

flutter:
  # No flutter-specific dependencies needed for this package
